import { Bot, Globe, Shield, Code2, Terminal, Wifi } from "lucide-react";

export const projects = [
  {
    id: 1,
    icon: Bot,
    title: "Astra AI Agent",
    shortDesc: "Advanced AI Telegram bot with GPT, voice & document generation.",
    description:
      "Astra is a fully autonomous AI agent running on Telegram. It integrates GPT for intelligent responses, supports bidirectional voice communication (STT/TTS), can autonomously generate and send Word, Excel, and PowerPoint documents on command. Built entirely in Python with the Telegram Bot API.",
    tags: ["Python", "Telegram API", "OpenAI", "TTS/STT", "python-docx", "openpyxl"],
    color: "#7c3aed",
    glow: "purple" as const,
    github: "#",
    demo: "#",
    status: "Active",
    highlights: [
      "Voice message input & AI audio response",
      "Document generation (Word, Excel, PowerPoint)",
      "Autonomous task execution via chat commands",
      "GPT-powered intelligent conversation",
      "File delivery directly to Telegram chats",
    ],
  },
  {
    id: 2,
    icon: Globe,
    title: "NEXUS Smart Home",
    shortDesc: "Smart life system with web dashboard, IoT control & voice commands.",
    description:
      "NEXUS is a complete smart home management system. It features a modern glassmorphism web dashboard with dark/light mode, Telegram-based voice and text command processing, SSL-secured local network access, and hardware IoT control. Designed with a focus on security and real-time responsiveness.",
    tags: ["Python", "Flask", "React", "WebSockets", "SSL", "IoT"],
    color: "#06b6d4",
    glow: "cyan" as const,
    github: "#",
    demo: "#",
    status: "Active",
    highlights: [
      "Real-time IoT device control via web dashboard",
      "Telegram voice/text command integration",
      "SSL-secured local network access",
      "Dark/light mode modern UI",
      "Confirmation-based safety controls",
    ],
  },
  {
    id: 3,
    icon: Shield,
    title: "Security Scanner",
    shortDesc: "Self-hosted vulnerability scanner with OWASP ZAP, Nuclei & Flask UI.",
    description:
      "A self-hosted automated security scanning platform integrating OWASP ZAP, Nuclei, and Nikto. It features a Flask web dashboard for report management and domain configuration, SQLite database for persistence, automated scheduled scans via cron jobs, and email alerting for high-risk findings.",
    tags: ["Python", "Flask", "Docker", "OWASP ZAP", "Nuclei", "SQLite"],
    color: "#10b981",
    glow: "emerald" as const,
    github: "#",
    demo: "#",
    status: "Complete",
    highlights: [
      "OWASP ZAP + Nuclei + Nikto integration",
      "Web dashboard for scan management",
      "Scheduled automated scans (cron)",
      "Email alerts for critical findings",
      "Docker Compose deployment",
    ],
  },
  {
    id: 4,
    icon: Code2,
    title: "Ibrat Talim Landing",
    shortDesc: "Premium landing page for an educational center in Tashkent.",
    description:
      "A visually immersive modern landing page for Ibrat Talim educational center. Features 3D tilt card animations, glassmorphism effects, animated hero with particle backgrounds, statistics counters, student testimonials, and full dark/light mode support. Optimized for all devices.",
    tags: ["HTML", "CSS", "JavaScript", "3D Animations", "Glassmorphism"],
    color: "#ec4899",
    glow: "pink" as const,
    github: "#",
    demo: "#",
    status: "Complete",
    highlights: [
      "3D tilt card animations",
      "Glassmorphism UI design",
      "Animated hero with particles",
      "Statistics & testimonials sections",
      "Full responsive dark/light mode",
    ],
  },
  {
    id: 5,
    icon: Terminal,
    title: "329 School Website",
    shortDesc: "High-end multi-page school website with premium animations.",
    description:
      "A stunning multi-page website for the 329th school in Tashkent. Built with pure HTML/CSS/JS featuring exclusive entrance animations, scroll-triggered effects, glassmorphism UI patterns, and an immersive user experience that sets it apart from typical school websites.",
    tags: ["HTML", "CSS", "JavaScript", "Scroll Effects", "Glassmorphism"],
    color: "#f59e0b",
    glow: "none" as const,
    github: "#",
    demo: "#",
    status: "Complete",
    highlights: [
      "Multi-page architecture",
      "Scroll-triggered animations",
      "Glassmorphism UI components",
      "Mobile-responsive design",
      "Optimized performance",
    ],
  },
  {
    id: 6,
    icon: Wifi,
    title: "Telegram Voice Bot",
    shortDesc: "Bidirectional voice bot with STT, TTS, and AI responses.",
    description:
      "A Telegram bot that processes incoming voice messages using Speech-to-Text, generates intelligent AI responses via GPT, and replies with both an audio file (TTS) and a text transcription for full accessibility. Every voice interaction is accompanied by written content.",
    tags: ["Python", "Telegram API", "SpeechRecognition", "gTTS", "OpenAI"],
    color: "#8b5cf6",
    glow: "purple" as const,
    github: "#",
    demo: "#",
    status: "Complete",
    highlights: [
      "Voice message recognition (STT)",
      "AI-generated intelligent responses",
      "Audio replies via TTS engine",
      "Text transcription with every audio",
      "Fully accessible dual-format output",
    ],
  },
];

export const certificates = [
  {
    id: 1,
    title: "C3SA",
    fullTitle: "Certified Cybersecurity Skills Associate (C3SA)",
    issuer: "CyberWarFare Labs",
    date: "2025",
    category: "Security",
    color: "#7c3aed",
    colorHex: "7c3aed",
    credentialId: "C3SA-2025",
    verified: true,
    image: "/src/Certificats/C3SA.png",
    description:
      "Validates foundational and practical cybersecurity skills including network security, vulnerability assessment, and ethical hacking fundamentals. Issued by CyberWarFare Labs.",
    skills: ["Network Security", "Vulnerability Assessment", "Ethical Hacking", "Security Tools"],
  },
  {
    id: 2,
    title: "CRTA",
    fullTitle: "Certified Red Team Analyst (CRTA)",
    issuer: "CyberWarFare Labs",
    date: "2025",
    category: "Security",
    color: "#ef4444",
    colorHex: "ef4444",
    credentialId: "CRTA-2025",
    verified: true,
    image: "/src/Certificats/CRTA.png",
    description:
      "Advanced certification in Red Team operations, adversarial simulation, and offensive security techniques. Covers penetration testing methodologies, Active Directory attacks, and real-world attack simulation.",
    skills: ["Red Teaming", "Penetration Testing", "Active Directory", "Offensive Security"],
  },
  {
    id: 3,
    title: "WEB-RTA",
    fullTitle: "Web Red Team Analyst (WEB-RTA)",
    issuer: "CyberWarFare Labs",
    date: "2025",
    category: "Security",
    color: "#06b6d4",
    colorHex: "06b6d4",
    credentialId: "WEB-RTA-2025",
    verified: true,
    image: "/src/Certificats/WEB-RTA.png",
    description:
      "Specialized certification focused on web application red teaming. Covers OWASP Top 10, advanced XSS/SQLi techniques, API security testing, and web vulnerability exploitation in real-world environments.",
    skills: ["Web App Hacking", "OWASP Top 10", "API Security", "XSS/SQLi"],
  },
];
